apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
  namespace: openshift-operators 
spec:
  channel: v2.2
  #chanel versions: https://www.ibm.com/docs/en/cloud-paks/cp-integration/2022.4?topic=reference-operator-channel-versions-this-release
  name: ibm-mq 
  source: ibm-operator-catalog 
  sourceNamespace: openshift-marketplace
