apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-event-stream-sub
  namespace: openshift-operators 
spec:
  channel: {###PROVIDE_CHANNEL_OPERATOR_HERE###}
  name: ibm-event-stream
  source: ibm-operator-catalog 
  sourceNamespace: openshift-marketplace
