apiVersion: operators.coreos.com/v1
kind: OperatorGroup
  name: ibm-integration-operatorgroup
  namespace: {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}
spec:
  targetNamespaces:
    - {###PROVIDE_YOUR_PROJECT_NAMESPACE_CP4X_HERE###}
  upgradeStrategy: Default
